# https://docs.travis-ci.com/user/languages/go/
language: go
sudo: false
go:
  - 1.9
  - 1.8
  - 1.7
matrix:
  fast_finish: true
  allow_failures:
    - go: 1.8
    - go: 1.7
install:
  - go get -t -v ./...
script:
  - go test -v ./...
